### ISSUE TITLE
Question about information required for training other than RGB Depth data

### ISSUE THREAD

**Issue by mohammad-saber** [Navhkrin/Bts-PyTorch#7]
Thank you very much for sharing your great code. I have a question about training process. 

Is there any additional information other than RGB and depth required for training? (Example: camera intrinsic, extrinsic, or other project specific information).

Thank you very much for your help.

**Comment by ErenBalatkan** [comment]
Greetings, your welcome. During training, only RGB and depth information is required. However, during inference, if you are using camera with different focal length than the camera of Kitti dataset, estimated depth values need to be scaled to ensure estimated depth is correct

This code already does the scaling automatically on predict function, you just need to plug in focal length of your camera in pixels. (If you are going to use this model only on Kitti dataset, then function already has default argument for Kitti which is 715)

```
def predict(model, input, is_channels_first=True, focal=715.0873):
    if is_channels_first:
        tensor_input = torch.tensor(input).unsqueeze(-1).to("cuda").float().transpose(0, 3).transpose(2, 3).transpose(1, 2)
    else:
        tensor_input = torch.tensor(input).unsqueeze(-1).to("cuda").float().transpose(0, 3).transpose(1, 2).transpose(2, 3)
    model_output = model(tensor_input, torch.tensor(focal).unsqueeze(0))[-1][0].detach().cpu().transpose(0, 1).transpose(1, 2).squeeze(-1)
    return model_output
```

**Comment by mohammad-saber** [comment]
Thank you very much. 

What about "NYU Depth V2 Dataset"?

In the paper, it is explained that "Using raw depth images and camera projections provided by the dataset, we align the image-depth pairs for accurate pixel registrations."

Therefore, I thought focal length was used during training.

**Comment by ErenBalatkan** [comment]
I havent worked with NYU Depth dataset and this repository only supports Kitti dataset, therefore if they are doing some additional processes for NYU dataset i do not know.
