### ISSUE TITLE
Question of depth output

### ISSUE THREAD

**Issue by y-fuku-local** [Navhkrin/Bts-PyTorch#8]
This model is trained by LiDAR data.
Therefore, it is possible to predict absolute distance, right?

**Comment by ErenBalatkan** [comment]
Yep, model outputs per-pixel distance in meters. Only thing you need to be careful is focal length of the camera. Outputs need to be scaled by the focal length of camera. 

Predict method already does the scaling automatically, you just need to put your camera's focal length as input
```
def predict(self, input, is_channels_first=True, focal=715.0873, normalize=False):
```
The default argument 715 is the focal length of Kitti dataset's camera

**Comment by y-fuku-local** [comment]
Thank you for your quick response.
I understood that is possible to predict absolute distance.
Regarding the answer, I want to confirm two things.

1. Scaled by the focal length is calculated by following formula.
    Is that correct?
    depth *= focal.view(-1, 1, 1, 1) / 715.0873

2.  KITTI datasets contain various focal lengths.
     Therefire, outputs need to be scaled by the focal length of camera.

     However, if all datasets are captured same camera(same focal length), it is not neccessary to be scaled by the focal length of 
    camera, right?

**Comment by ErenBalatkan** [comment]
1. Formula is correct

2. Indeed, no scaling needs to be done if dataset contains only 1 focal length, what essentially happens is, model fits into one focal length (in case of Kitti, the average focal length of dataset), and if we want to make inference with different camera we need to scale depths based on focal length.

**Comment by y-fuku-local** [comment]
Thank you your response. I understood.

In addition I want to confirm about LPG processing.
I couldn't understand the meaning of following formula.

BTS.py
------------------------------------------------------------------------------------------------------------------
n1 = plane_eq_expanded[:, 0, :, :]
n2 = plane_eq_expanded[:, 1, :, :]
n3 = plane_eq_expanded[:, 2, :, :]
n4 = plane_eq_expanded[:, 3, :, :]

u = self.u.repeat(plane_eq.size(0), plane_eq.size(2) * int(self.scale), plane_eq.size(3)).to(device)
u = (u - (self.scale - 1) * 0.5) / self.scale

v = self.v.repeat(plane_eq.size(0), plane_eq.size(2), plane_eq.size(3) * int(self.scale)).to(device)
v = (v - (self.scale - 1) * 0.5) / self.scale

d = n4 / (n1 * u + n2 * v + n3)
d = d.unsqueeze(1)
------------------------------------------------------------------------------------------------------------------

Regarding the formula, are there any web pages or refferences that is possible to understand?
Sorry for asking you so many questions.

**Comment by ErenBalatkan** [comment]
This formula calculates Ray-Plane Intersection location, you can search by that name, im not sure if there are helpful pages for that.

Essentially, n1, n2, n3 are parameters for the plane normal and n4 is estimated depth value

We want to generate higher resolution depth map based on these parameters,

u and v are our tiling indexes, so basically, if we are upscaling by factor of 2x2, u and v are of following format

[-0.5, 0,5, -0.5, 0,5]

if we were upscaling by a factor of 3, they would be in following format

[-0.333, 0, 0.333, -0.333, 0, 0.333]

Here is my old cuda kernel based implementation, it may be easier to understand, this implementation is faster aswell but because it requires Numba and works only on Nvidia cards i switched to new implementation which is based on official implementation.

```
@cuda.jit
def Cuda_LPG_Forward(plane_parameters, scale, result):
    batch_idx = cuda.threadIdx.z
    pixel_y = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x
    pixel_x = cuda.blockIdx.y * cuda.blockDim.y + cuda.threadIdx.y

    if pixel_x < plane_parameters.shape[3] and pixel_y < plane_parameters.shape[2]:
        n1 = plane_parameters[batch_idx, 0, pixel_y, pixel_x]
        n2 = plane_parameters[batch_idx, 1, pixel_y, pixel_x]
        n3 = plane_parameters[batch_idx, 2, pixel_y, pixel_x]
        n4 = plane_parameters[batch_idx, 3, pixel_y, pixel_x]

        for ii in range(scale):
            for jj in range(scale):

                v = (ii - (scale-1) / 2.0) / scale / 715.0
                u = (jj - (scale-1) / 2.0) / scale / 715.0

                numerator = n4
                denominator = (n1*u + n2*v + n3)

                result[batch_idx, 0, pixel_y*scale + ii, pixel_x*scale + jj] = numerator/denominator
```

**Comment by y-fuku-local** [comment]
Thank you for sending code and your  description.
Regarding the Ray-Plane Intersection location, I found reference page.
https://nghiaho.com/?page_id=363

However, I couldn't understand about the formula『n4/ (n1*u + n2*v + n3』

**Comment by ErenBalatkan** [comment]
It is same as the formula at the end of the page you linked,

D = N4
A = N1
B = N2
C = N3

**Comment by y-fuku-local** [comment]
Thank you for your response.
I understood the meaning of formula.

**Comment by ErenBalatkan** [comment]
Your welcome, closing the issue
