### ISSUE TITLE
GPU Memory Usage Issue

### ISSUE THREAD

**Issue by alpertungakin** [Navhkrin/Bts-PyTorch#9]
Hello,
I'm trying to use BTSController.predict() on the images taken with Android phone camera by scaling according to focal length and getting "runtimeerror: cuda out of memory. tried to allocate..." error. The error is disappearing by reducing the image size but it means loss of accuracy. I've also tried to divide images into equal 32x X 32x small pieces, but this process loses the semantic relationship between objects. Please correct if I am wrong with these conclusions. I did some garbage collection edits in predict method but nothing has changed. Im using GTX 1050 4GB DDR5 GPU. What could you suggest about it? Thanks!

**Comment by ErenBalatkan** [comment]
Backbone I have used in this repository is DenseNet-161, which is computationally and memory-wise very expensive. I would suggest changing backbone to something lighter and re-training the model.
https://github.com/ErenBalatkan/Bts-PyTorch/blob/28f7e5d2c5a646fbbb539626f23154278315b3a1/BTS.py#L234

If that is not an option, you can try to use 16-bit model instead by calling .half() on model. For more information about this please check
https://discuss.pytorch.org/t/training-with-half-precision/11815

**Comment by alpertungakin** [comment]
Half precision did not affect worthy. I will try to retrain with a lightweight model. Thanks for the support.
